const Type = {
  ADD_CONTACT: 'ADD_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',
  FILTER_CONTACTS: 'FILTER_CONTACTS',
  GET_CONTACTS_FROM_LS: 'GET_CONTACTS_FROM_LS',
};

export default Type;
